# Generated by Django 4.1.7 on 2023-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('quantity', models.PositiveSmallIntegerField(default=0, max_length=1, verbose_name='Сколько раз активирован код')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
        ),
    ]
