# Generated by Django 4.1.7 on 2023-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='code',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сколько раз активирован код'),
        ),
    ]
