# Generated by Django 4.1.7 on 2023-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_code_code_alter_code_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activité'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de génération'),
        ),
        migrations.AlterField(
            model_name='code',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Combien de fois activé'),
        ),
    ]
